### ISSUE TITLE
CloudConvert takes a lot of time

### ISSUE THREAD

**Issue by Ahitaf** [cloudconvert/cloudconvert-php#39]
Hello;
I'm using CloudConvert to convert a .ppt to pdf, and it takes a lot of time(+30 secs) to respond; 
how can I reduce this time please? any body can help me!!

**Comment by josiasmontag** [comment]
Conversion time depends on many factors: 

- size and complexity of the file
- used upload method of the input file (upload, download...)
- used download method of the output file (download, s3, ftp...)
- your servers internet connection 
- ...

Does converting the same file on the cloudconvert.com website take less time? If not, this is most likely related to the file. In this case the issue is not related to the PHP wrapper. You can provide the file to support@cloudconvert.com for further investigation. 

Feel free to comment and reopen if there is an issue directly related to the PHP wrapper.

**Comment by Ahitaf** [comment]
Thank you @josiasmontag, you're right, even with the website takes many seconds/minutes to convert the file; it all depends on the size
thank you again
