### ISSUE TITLE
Improve documentation

### ISSUE THREAD

**Issue by filerun** [cloudconvert/cloudconvert-php#92]
Hi, I would really appreciate if you would:
- include some error reporting/handling examples
- give an example on how to list supported formats using this new library
- give some info on what the methods return and how to tell if the actions were successful or not
- give info on tasks names (accepted formats, expected to be unique or not?)
- give an example on how to check for the status of a task

**Comment by josiasmontag** [comment]
Sure, there is always room to make the documentation more detailed. However, the README file contains the typical example use cases. For details about specific methods you can also check the source code directly, which has DocComments and is pretty straightforward.

> * include some error reporting/handling examples

You can find all exceptions here: https://github.com/cloudconvert/cloudconvert-php/tree/master/src/Exceptions

> * give an example on how to list supported formats using this new library

This is currently not supported by the SDK. PRs are always welcome.

> * give some info on what the methods return and how to tell if the actions were successful or not

The methods return the Job/Task object if successful. Otherwise they throw an exception.

> * give info on tasks names (accepted formats, expected to be unique or not?)

This is documented here: https://cloudconvert.com/api/v2/jobs#jobs-create

> * give an example on how to check for the status of a task

```php
$cloudconvert->tasks()->get('task-id') // returns task object
```

**Comment by filerun** [comment]
> > * give an example on how to list supported formats using this new library
> 
> This is currently not supported by the SDK. PRs are always welcome.

Managed with this:
```
$ccHttp = new \CloudConvert\Transport\HttpTransport([]);
$response = $ccHttp->get($ccHttp->getBaseUri() .'/convert/formats', ['filter[input_format]' => \S::forURL($ext)]);
json_decode($response->getBody(), true);
```

Thanks for the quick reply!

**Comment by joshv2** [comment]
Can you also please give an example of how to access the user's account infor (e.g. remaining credits, etc). Thanks.
